# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'gameofchats' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gameofchats

#pod 'Firebase/Database'
#pod 'Firebase/Auth'
#pod 'Firebase/Storage'
#pod 'Firebase/Core'

pod 'Firebase'
pod 'Firebase/Storage'
pod 'FirebaseAnalytics'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'

pod 'FirebaseCore'
pod 'FirebaseMessaging'
pod 'Firebase/Messaging'

end
